version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: siddharth
      POSTGRES_PASSWORD: siddharth
      POSTGRES_DB: file_system
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data: