version: '3.8'

services:
  # Redis service
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  # PostgreSQL database service
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: siddharth
      POSTGRES_PASSWORD: siddharth
      POSTGRES_DB: file_system
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  # Go application service
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "AKIAQXHOIJXXON7TKMET"
      AWS_SECRET_ACCESS_KEY: "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"
      AWS_REGION: "eu-north-1"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: siddharth
      DB_PASSWORD: siddharth
      DB_NAME: file_system
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    depends_on:
      - db
      - redis

volumes:
  db-data: